"""Transport protocol definitions."""

from __future__ import annotations

from typing import Any, Protocol


class TransportProtocol(Protocol):
    """Protocol for transport implementations."""

    def get_base_url(self) -> str: ...

    @property
    def auth_mode(self) -> str: ...


class SyncTransportProtocol(TransportProtocol, Protocol):
    """Protocol for synchronous transport."""

    def get(self, url: str, params: dict[str, Any] | None = None) -> Any: ...
    def post(self, url: str, body: Any = None, params: dict[str, Any] | None = None) -> Any: ...
    def put(self, url: str, body: Any = None) -> Any: ...
    def patch(self, url: str, body: Any = None) -> Any: ...
    def delete(self, url: str) -> Any: ...
    def put_csv(self, url: str, body: bytes | str) -> Any: ...
    def put_gzip(self, url: str, body: bytes) -> Any: ...
    def get_csv(self, url: str, params: dict[str, Any] | None = None) -> Any: ...


class AsyncTransportProtocol(TransportProtocol, Protocol):
    """Protocol for asynchronous transport."""

    async def get(self, url: str, params: dict[str, Any] | None = None) -> Any: ...
    async def post(self, url: str, body: Any = None, params: dict[str, Any] | None = None) -> Any: ...
    async def put(self, url: str, body: Any = None) -> Any: ...
    async def patch(self, url: str, body: Any = None) -> Any: ...
    async def delete(self, url: str) -> Any: ...
    async def put_csv(self, url: str, body: bytes | str) -> Any: ...
    async def put_gzip(self, url: str, body: bytes) -> Any: ...
    async def get_csv(self, url: str, params: dict[str, Any] | None = None) -> Any: ...
